# Generated by Django 5.2.6 on 2025-09-04 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_years_on_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='years_on_site',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
