# Generated by Django 5.2.6 on 2025-09-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ad_updated_at_alter_ad_location_alter_ad_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
